# Generated by Django 6.1.1 on 2026-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kc_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
