# Generated by Django 6.1.1 on 2026-09-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_kc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_sid', models.CharField(max_length=255, unique=True)),
                ('django_session_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
