# Generated by Django 6.1.1 on 2026-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_oidcsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kc_id',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
