name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: user-service
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d user-service"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.19"

      - name: Install dependencies
        working-directory: services/user-service
        run: uv sync

      - name: Run Django tests
        working-directory: services/user-service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: user-service
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres

          KC_SERVER_URL: http://localhost:8080
          KC_BROWSER_SERVER_URL: http://localhost:8080
          KC_REALM: rr-store
          OIDC_RP_CLIENT_ID: test-client
          OIDC_RP_CLIENT_SECRET: test-secret
          KC_ADMIN_CLIENT_ID: test-admin-client
          KC_ADMIN_CLIENT_SECRET: test-admin-secret

        run: uv run python manage.py test

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: frontend/web/package-lock.json

      - name: Install dependencies
        working-directory: frontend/web
        run: npm ci

      - name: Run lint
        working-directory: frontend/web
        run: npm run lint

      - name: Build frontend
        working-directory: frontend/web
        run: npm run build
